
cmake_minimum_required(VERSION ${CMAKE_VERSION}) # this file comes with cmake

set(command "/opt/homebrew/bin/cmake;-G;Unix Makefiles;-DCMAKE_POLICY_VERSION_MINIMUM=3.5;-DCMAKE_BUILD_TYPE=Release;-DCMAKE_CXX_COMPILER=/usr/bin/c++;-DCMAKE_CXX_FLAGS= -Wc++11-narrowing -Wsign-compare -Wsometimes-uninitialized -Wconditional-uninitialized -Wheader-guard -Warray-bounds -Wcomment -Wtautological-compare -Wstrncat-size -Wloop-analysis -Wbool-conversion -m64 -pipe -W -Wall -Woverloaded-virtual -fsigned-char -fsized-deallocation -fno-common -Qunused-arguments -pthread -stdlib=libc++ ;-DCMAKE_C_COMPILER=/usr/bin/cc;-DCMAKE_C_FLAGS= -m64 -pipe -W -Wall -fsigned-char -fno-common -Qunused-arguments -pthread;-DCMAKE_INSTALL_INCLUDEDIR=/Users/sanilawijesekara/Documents/gsoc/Root/root-GSOC/root-build/include;-DCMAKE_INSTALL_LIBDIR=/Users/sanilawijesekara/Documents/gsoc/Root/root-GSOC/root-build/lib;-DCMAKE_INSTALL_PREFIX=/Users/sanilawijesekara/Documents/gsoc/Root/root-GSOC/root-build;-DTBBMALLOC_BUILD=OFF;-DTBBMALLOC_PROXY_BUILD=OFF;-DTBB_ENABLE_IPO=OFF;-DTBB_STRICT=OFF;-DTBB_TEST=OFF;-GUnix Makefiles;-S;/Users/sanilawijesekara/Documents/gsoc/Root/root-GSOC/root-build/TBB-prefix/src/TBB;-B;/Users/sanilawijesekara/Documents/gsoc/Root/root-GSOC/root-build/TBB-prefix/src/TBB-build")
set(log_merged "")
set(log_output_on_failure "1")
set(stdout_log "/Users/sanilawijesekara/Documents/gsoc/Root/root-GSOC/root-build/TBB-prefix/src/TBB-stamp/TBB-configure-out.log")
set(stderr_log "/Users/sanilawijesekara/Documents/gsoc/Root/root-GSOC/root-build/TBB-prefix/src/TBB-stamp/TBB-configure-err.log")
execute_process(
  COMMAND ${command}
  RESULT_VARIABLE result
  OUTPUT_FILE "${stdout_log}"
  ERROR_FILE "${stderr_log}"
)
macro(read_up_to_max_size log_file output_var)
  file(SIZE ${log_file} determined_size)
  set(max_size 10240)
  if (determined_size GREATER max_size)
    math(EXPR seek_position "${determined_size} - ${max_size}")
    file(READ ${log_file} ${output_var} OFFSET ${seek_position})
    set(${output_var} "...skipping to end...\n${${output_var}}")
  else()
    file(READ ${log_file} ${output_var})
  endif()
endmacro()
if(result)
  set(msg "Command failed: ${result}\n")
  foreach(arg IN LISTS command)
    set(msg "${msg} '${arg}'")
  endforeach()
  if (${log_merged})
    set(msg "${msg}\nSee also\n  ${stderr_log}")
  else()
    set(msg "${msg}\nSee also\n  /Users/sanilawijesekara/Documents/gsoc/Root/root-GSOC/root-build/TBB-prefix/src/TBB-stamp/TBB-configure-*.log")
  endif()
  if (${log_output_on_failure})
    message(SEND_ERROR "${msg}")
    if (${log_merged})
      read_up_to_max_size("${stderr_log}" error_log_contents)
      message(STATUS "Log output is:\n${error_log_contents}")
    else()
      read_up_to_max_size("${stdout_log}" out_log_contents)
      read_up_to_max_size("${stderr_log}" err_log_contents)
      message(STATUS "stdout output is:\n${out_log_contents}")
      message(STATUS "stderr output is:\n${err_log_contents}")
    endif()
    message(FATAL_ERROR "Stopping after outputting logs.")
  else()
    message(FATAL_ERROR "${msg}")
  endif()
else()
  if(NOT "Unix Makefiles" MATCHES "Ninja")
    set(msg "TBB configure command succeeded.  See also /Users/sanilawijesekara/Documents/gsoc/Root/root-GSOC/root-build/TBB-prefix/src/TBB-stamp/TBB-configure-*.log")
    message(STATUS "${msg}")
  endif()
endif()
